######################################################################
# Automatically generated by qmake (3.0) ?? 2? 23 11:08:03 2019
######################################################################

TEMPLATE = app
TARGET = titlebar
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += titlebar.h
SOURCES += main.cpp \
    titlebar.mm
    
LIBS += -framework AppKit
