######################################################################
# Automatically generated by qmake (3.0) ?? 2? 23 11:08:03 2019
######################################################################

TEMPLATE = app
TARGET = NotificationCenter
INCLUDEPATH += .

# Input
HEADERS += NotificationCenter.h
SOURCES += main.cpp \
    NotificationCenter.mm
    
LIBS += -framework AppKit
